# Generated by Django 5.1.15 on 2026-06-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('ble_id', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['sitio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(choices=[('museo', 'Museo'), ('arqueologico', 'Centro arqueológico')], default='arqueologico', max_length=20)),
                ('mapa_top', models.FloatField(default=50)),
                ('mapa_left', models.FloatField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_total_seg', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('baliza_abandono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandonos', to='api.baliza')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_seg', models.PositiveIntegerField(default=0)),
                ('repeticiones_narracion', models.PositiveIntegerField(default=0)),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baliza')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.recorrido')),
            ],
        ),
        migrations.AddField(
            model_name='baliza',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balizas', to='api.sitio'),
        ),
    ]
