# Generated by Django 5.1.15 on 2026-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='latitud',
            field=models.FloatField(default=-12.0464),
        ),
        migrations.AddField(
            model_name='sitio',
            name='longitud',
            field=models.FloatField(default=-77.0428),
        ),
    ]
