# Generated by Django 5.1.15 on 2026-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitio_latitud_sitio_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='baliza',
            name='operativa',
            field=models.BooleanField(default=True),
        ),
    ]
